# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  database: db/development.sqlite3
  encoding: utf8

test:
  <<: *default
  database: db/test.sqlite3
  encoding: utf8

production:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: billybo_production
  pool: 5
  username: <%= ENV['BILLYBO_DATABASE_USER'] %>
  password: <%= ENV['BILLYBO_DATABASE_PASSWORD'] %>